### ISSUE TITLE
Output: Automatically generate benchmark CSVs from script

### ISSUE THREAD

**Issue by weiya711** [tensor-compiler/array-programming-benchmarks#12]
Need to automatically generate CSV data from taco-bench googletest and python-bench googletest in a designated csv directory. 

This will be used for automatic import into the benchmarking google sheet

**Comment by rohany** [comment]
can the directory be named `results/`?

**Comment by weiya711** [comment]
Sure. currently the format for the output files are `<repo>/csvs/taco` and `<repo>/csvs/numpy` with the outputfile name as `$(BENCHNAME)bench_$(date Y_m_d_HMS).csv`

But let me change it results really quickly and then I'll push the changes to the makefile

**Comment by rohany** [comment]
Did you get a chance to see what the "extra column" data looks like in the CSV? I tried to add some extra columns to the googletest benchmarks using
```
  state.Counters["dimx"] = ...
  state.Counters["dimy"] = ...
```
and these showed up in the user friendly output as in the same column, so I'm not sure if it will be that CSV friendly

**Comment by weiya711** [comment]
Not yet I'm going to try that now. I just pushed the changes that add in  `<repo>/results/taco` and `<repo>/results/numpy` with the output filename `$(BENCHNAME)bench_$(date Y_m_d_HMS).csv` at commit e8c6788

I'll look into adding columns for pytest. Also based on the current pytest csv format it is unclear to me where the iterations and statistic values went or what the units are. If you look at the [google sheet](https://docs.google.com/spreadsheets/d/1cJHC5mS3HA3SID-l1Tw3HSmfszyyZLYwFZbQxDWOwR8/edit?usp=sharing) it seems that there is only one column for values

**Comment by weiya711** [comment]
This is mainly resolved. Just need to ensure that TACO and Python tensor names (for frostt and suitesparse) are identical. AS an example, chicago_crime vs. chicago-crime will cause an error in google sheets.

**Comment by rohany** [comment]
> chicago_crime vs. chicago-crime will cause an error in google sheets.

The variations in the FROSTT tensors are fixed now

**Comment by rohany** [comment]
Going to close this since the loose-ends have been tied up.
