### ISSUE TITLE
data: implement a suitesparse matrix loader

### ISSUE THREAD

**Issue by rohany** [tensor-compiler/array-programming-benchmarks#2]
This should load the necessary matrix in from data/suitespace

**Comment by stephenchouca** [comment]
Not sure if you’re already aware, but both the TACO C++ and Python APIs provide a `read` function that can be used to load SuiteSparse matrices (in MTX files) and FROSTT tensors (in TNS files).

**Comment by weiya711** [comment]
Yea Fred showed us in file_io_*

**Comment by rohany** [comment]
Yup, I'm using these in https://github.com/tensor-compiler/array-programming-benchmarks/blob/a58fc6cdc8f590464bc870e3ed6ca3cf7bf14437/taco/bench.cpp#L29. It doesn't look like the pydata/sparse and scipy/sparse have many options for reading and writing different tensor file formats, so those we'll have to write by hand.

**Comment by stephenchouca** [comment]
> . It doesn't look like the pydata/sparse and scipy/sparse have many options for reading and writing different tensor file formats, so those we'll have to write by hand.

For matrices at least, you might be able to use `pytaco.to_sp_csr` or `pytaco.to_sp_csc` in conjunction with `pytaco.read` to read matrices from file (and `pytaco.from_sp_csr` or `pytaco.from_sp_csc` in conjunction with `pytaco.write` to write matrices to file). For higher-order tensors, you probably do need something custom (though you might still be able to utilize `pytaco.read` and `pytaco.write`).

**Comment by rohany** [comment]
It looks like scipy supports reading the matrix market format, https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.mmread.html, so we can use this to read suitesparse tensors and then have pydata sparse convert from the scipy.sparse tensors.
