### ISSUE TITLE
try to get some parallelism / openmp running on TACO's benchmarks

### ISSUE THREAD

**Issue by rohany** [tensor-compiler/array-programming-benchmarks#22]
numpy is most likely parallelizing operations (we need to look into how to control the number of threads here), so we should as well.

**Comment by rohany** [comment]
Based on some googling, we need to set all of 
```
OMP_NUM_THREADS=1
OPENBLAS_NUM_THREADS=1 
MKL_NUM_THREADS=1 
VECLIB_MACIMUM_THREADS=1 
NUMEXPR_NUM_THREADS=1
```

`OPENBLAS_NUM_THREADS` seems to control the number of threads for matrix multiply.

**Comment by rohany** [comment]
playing around with these different settings didn't appear to change the runtime of pydata's benchmarks

**Comment by stephenchouca** [comment]
For reference, you can build TACO with OpenMP support by running `make OPENMP=ON`. The TACO mxv benchmark in `taco/graphblas.cpp` shows how you can configure TACO to run with arbitrary numbers of OpenMP threads.
